### ISSUE TITLE
Appender not logging

### ISSUE THREAD

**Issue by schh** [plmwong/log4net-raygun#19]
Ive got a ConsoleApplication and two WPF Applications. All 3 have have identical configurations. My console app raygun appender works fine, but none of my WPF appenders work.

My rolling file appender works fine so log4net seems properly configured. 

I do the following in my App.xaml.cs

```
void ConfigureLogging()
{
   log4net.Config.XmlConfigurator.Configure();

   LogicalThreadContext.Properties[RaygunAppenderBase.PropertyKeys.Tags] = "fordon";
}
```
And my App.config

```
<root>
      <appender-ref ref="RollingFileAppender"/>
      <appender-ref ref="RaygunAppender"/>
    </root>
    <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
      <threshold value="ERROR"/>
      <file value="logs\\Log.txt"/>
      <appendToFile value="true"/>
      <encoding value="utf-8"/>
      <countDirection value="1"/>
      <maxSizeRollBackups value="2"/>
      <maximumFileSize value="10MB"/>
      <preserveLogFileNameExtension value="true"/>
      <rollingStyle value="Size"/>
      <staticLogFileName value="true"/>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %level %logger - %message%newline"/>
      </layout>
    </appender>
    <appender name="RaygunAppender" type="log4net.Raygun.RaygunAppender, log4net.Raygun">
      <threshold value="FATAL" />
      <apiKey value="apikey" />
      <retries value="15" />
      <timeBetweenRetries value="00:01:00" />
      <onlySendExceptions value="true" />
      <sendInBackground value="false" />
    </appender>
```

I've been scratching my head for a few hours. i Cant figure out why its not working. Any help would be appreciated

**Comment by plmwong** [comment]
Hi there,

Can you try turning on the log4net Internal Debug, and seeing if anything turns up in those logs? https://stackoverflow.com/questions/756125/how-to-track-down-log4net-problems

If you're still stuck, feel free to configure a trace listener as described in the above link and attach a log or excerpt of a log here, and I'll have a look.

Thanks!

**Comment by schh** [comment]
Ok so i see the problem clear as day after a good nights rest. I set the threshold to FATAL when im logging ERROR. Thanks for your help all the same!

**Comment by plmwong** [comment]
Awesome, glad you were able to figure things out!
