### ISSUE TITLE
Support for upcoming Raygun 4.0

### ISSUE THREAD

**Issue by plmwong** [plmwong/log4net-raygun#4]
https://raygun.io/blog/2014/10/heads-raygun4net-4-0-coming-soon/

With the upcoming Raygun version 4.0 the MVC and API support will be moved into their own NuGet packages. 
Consider changing log4net.Raygun dependencies to support either one of the MVC and API packages.

It is not possible to use log4net.Raygun in a MVC/WebAPI project that references Raygun4Net.WebApi and/or Raygun4Net.Mvc packages.

----------------------------------------
- Bitbucket: https://bitbucket.org/plmw/log4net.raygun/issue/4
- Originally reported by: [girtsl](http://bitbucket.org/girtsl)
- Originally created at: 2014-10-22T08:53:19.199

**Comment by plmwong** [comment]
I'll definitely be looking into the split and what impact that would have. Ideally I would like to avoid having separate packages for each of the three Raygun packages, though that's what it's looking like so far looking through how they've been split up.

----------------------------------------
Original comment by: Phillip Wong

**Comment by plmwong** [comment]
Hi!

Any update on this issue?

I have opened an issue with Raygun that might help you with this - https://github.com/MindscapeHQ/raygun4net/issues/223

Cheers,
Girts

----------------------------------------
Original comment by: [girtsl](http://bitbucket.org/girtsl)

**Comment by plmwong** [comment]
Heya,

Sorry, I've had a little trouble finding the time for looking into this particular change. But as soon as I can, I will have another look at how I could restructure log4net.Raygun, and at least try to separate out the things that reference the RaygunClient in the general Mindscape.Raygun4Net package so that the WebApi version of the client can be more easily hooked in instead.


Phillip

----------------------------------------
Original comment by: Phillip Wong

**Comment by plmwong** [comment]
A work-progress will be in the feature/raygun4split branch (https://bitbucket.org/plmw/log4net.raygun/branch/feature/raygun4split). I have kept the classes that depend on a concrete implementation of RaygunClientBase / RaygunMessageBuilder in log4net.Raygun and moved everything else to log4net.Raygun.Core.

So hopefully it should be possible to create a log4net.Raygun.WebApi assembly which its own implementations of RaygunAppender (inheriting from RaygunAppenderBase), IRaygunClient and IRaygunMessageBuilder, using the Mindscape.Raygun4Net.WebApi versions of RaygunClientBase etc. I'm still not entirely sure I would be keen to maintain multiple packages myself, but at least this way things are extensible enough if someone else wants to try building upon what I've got.

I still need to pull out the System.Web reference from log4net.Raygun.Core as well (since one of the benefits of using WebApi is not to have to go anywhere near that assembly). But making some headway I think.

----------------------------------------
Original comment by: Phillip Wong

**Comment by plmwong** [comment]
Cool! I suggest you wait a bit and see what the guys at Raygun will do regarding the split - see the github issue link in my previous comment. They seem to support my suggestion which would not require you to split up the packages.

----------------------------------------
Original comment by: [girtsl](http://bitbucket.org/girtsl)

**Comment by plmwong** [comment]
Thanks :) I will continue to tinker, but yeah, will hold off for a bit to see what happens on that front.

----------------------------------------
Original comment by: Phillip Wong

**Comment by girtsl** [comment]
Hi,
Mindscape have made progress in this field :)
https://github.com/MindscapeHQ/raygun4net/issues/223#issuecomment-77797961
https://raygun.io/blog/2015/03/new-release-raygun4net-5-0/

**Comment by plmwong** [comment]
Awesome, I'll pull down raygun4net 5.0 and have a look at the changes sometime this week.

**Comment by plmwong** [comment]
I've had a quick look to get a feel for the changes, and have asked if Mindscape could push down the `void Send(RaygunMessage raygunMessage)` method down to the base class, since that's the only method I call on the `RaygunClient` from log4net.Raygun. It would mean I could have all the core code the same and just build against the RaygunClientBase.

Even with this change, since there are different `RaygunClient` implementations in separate top-level projects/packages (understandably), I'll probably have to still go with a Core assembly which is built against their core Raygun4Net assembly, and then have a thin assembly/package per implementation that will simply wire up the appender with the corresponding `RaygunClient` implementation to use for sending the messages. This is very similar to what I already have in the feature/raygun4split branch.

Alternatively, I could add another (mandatory) configuration setting for the user to configure and point to the appropriate `RaygunClient` implementation they would like to use. This would be easier for me, and be flexible, but would add an extra setup hoop for a dev to jump through, which I would probably prefer to avoid requiring people to do.

**Comment by plmwong** [comment]
@girtsl I created a pre-release of log4net.Raygun 4.0, in which I've split out the code into three:
* `log4net.Raygun.Core` - Core code dependent on the core Mindscape.Raygun4Net.Core code.
* `log4net.Raygun` - Version of the appender which depends on the RaygunClient in Mindscape.Raygun4Net4. I.e., the one used by both the main Mindscape.Raygun4Net and Mindscape.Raygun4Net.Mvc packages.
* `log4net.Raygun.WebApi` - Version of the appender which depends on the RaygunWebApiClient and RaygunWebApiMessageBuilder in Mindscape.Raygun4Net.WebApi. Note that in order for the Http details to be logged, you need to write the HttpRequest into the log4net LogicalThreadContext so that the appender can find it throughout the request. This should be possible either through the controller directly, or by adding the RaygunHttpRequestHandler to the WebApi MessageHandlers.

Any use will at least require references to log4net.Raygun.Core.dll and Mindscape.Raygun4Net.dll, along with the appropriate DLLs for the app (log4net.Raygun.WebApi + Mindscape.Raygun4Net.WebApi or log4net.Raygun + Mindscape.Raygun4Net.Mvc).

The pre-release can be found at https://www.nuget.org/packages/log4net.Raygun/4.0.0.34385-pre, let me know how things go with it. I've gotten it working on some playground WebApi and Mvc projects, but I'll be continuing to test.

**Comment by girtsl** [comment]
Hi! Sorry, I've been quite busy lately and haven't had the time to check up on the updates.

Regarding your comment from 3 days ago:
If Raygun would pull up the `void Send(RaygunMessage raygunMessage)` method to `RaygunClientBase` class - would that mean that log4net.raygun would work with any single one of the 3 packages provided by Raygun - generic, mvc and web api? Of course, you would need a separate package for each of those, unless Raygun releases a core package...
I also like the idea about passing in a configured RaygunClient instance as that would fit my scenario very well. I can see this work as an optional configuration setting - accept a type name that implements your raygun client factory interface. If it's provided, use the specified factory, otherwise use your default (current) implementation. It's up to the dev then to implement the factory interface and supply the raygun client instance.
I hope to free up some time next week to check your latest changes and hopefully provide some feedback.

**Comment by girtsl** [comment]
@plmwong, I had some time today to look at the pre-release. 

What's the advantage of shipping `log4net.Raygun.WebApi` assembly with the `log4net.Raygun` package that has a dependency on `Mindscape.Raygun4Net`? Even more so if the reference is not added automatically. I suspect that no devs are adding references manually these days...

It seems to me that it should be put into its own package `log4net.Raygun.WebApi` that takes dependency only on `Mindscape.Raygun4Net.WebApi`. That way, if I already have the `Mindscape.Raygun4Net.WebApi` package installed, I don't need `Mindscape.Raygun4Net`. Same case with MVC - if I already have `Mindscape.Raygun4Net.Mvc` installed - I could add `log4net.Raygun.Mvc` and get rid of `Mindscape.Raygun4Net` altogether.
`log4net.Raygun` could work against `Mindscape.Raygun4Net` and be used in non-WebApi and non-MVC projects.

Alternatively, since Mindscape have made all of their 3 packages compatible, `log4net.Raygun` could simply take dependency on `Mindscape.Raygun4Net` and not bother with WebApi or Mvc at all.

**Comment by plmwong** [comment]
Apologies for the confusion.

`log4net.Raygun.WebApi` is only in the main package fro the pre. I didn't want to commit to having a separate package until it was clear that it was the way to go.

Both `Mindscape.Raygun4Net` and `Mindscape.Raygun4Net.Mvc` use the 'standard' RaygunClient in the `Mindscape.Raygun4Net4.dll` assembly (both of the NuGet packages include this assembly). So using the standard `log4net.Raygun` package is straight forward, as everything is DLL compatible with each other.

However, `Mindscape.Raygun4Net.WebApi` uses its own implementation of the RaygunClient called `RaygunWepApiClient`. It does this to support WebApi's disconnection from the behemoth of System.Web. Also, because the details of the http request are on the HttpRequestMessage, and not simply taken from the HttpContext, the way that RaygunMessages are built needs to be different for this use case.

So `log4net.Raygun.WebApi` is intended to be the out-of-the-box appender to use for those already using `Mindscape.Raygun4Net.WebApi`, and don't wish to add an additional dependency on System.Web. Hence this will probably be another package.

**Comment by girtsl** [comment]
Thanks, that clears things up a bit. My point about having 3 separate packages still stands - as a developer I would like to only install packages that are necessary. 
What do you think?

**Comment by plmwong** [comment]
Yeah that makes sense, I will break down things out into the following NuGet packages:
* `log4net.Raygun` - Core + log4net.Raygun
* `log4net.Raygun.Mvc` - Same assemblies as above, but has a declared NuGet dependency of Mindscape.Raygun4Net.Mvc instead of Mindscape.Raygun4Net
* `log4net.Raygun.WebApi` - Core + log4net.Raygun.WebApi
* `log4net.Raygun [1.2.10]` - The main package for the older 1.2.10 log4net since the most likely use case is in slightly older applications.

**Comment by girtsl** [comment]
Great! Just installed the latest version of all 3 packages - log4net.Raygun in a console application and both log4net.Raygun.Mvc and log4net.Raygun.WebApi in a Mvc+WebApi project. It seems that they all work as expected.
I guess this issue can be closed now.
Thanks!
