### ISSUE TITLE
Consider implementing a hook to inject a configured Raygun client instance

### ISSUE THREAD

**Issue by girtsl** [plmwong/log4net-raygun#6]
Please take a look at this question on [StackOverflow](http://stackoverflow.com/questions/23634472/using-ioc-in-a-custom-log4net-appender).
I'm not sure how well this aligns with log4net design principles, but using the same approach I was able to put together a log4net.raygun implementation that would obtain an instance of Raygun client configured by the host application.
The pros for such feature include but are not limited to: taking advantage of Raygun's means of configuration, smaller memory footprint.

If you consider this feature worth adding to the project, please also consider changing the raygun message building logic - the `log4net.Raygun.RaygunMessageBuilder` implementation is currently dettached from the `RaygunClient` (or `log4net.Raygun.Core.IRaygunClient`) instance and does not use the property values set on it - `ApplicationVersion` to name one.

**Comment by plmwong** [comment]
Added in a configuration property on the appender which can be pointed to an implementation of `IRaygunClientFactory`. This gives developers control over the construction of RaygunClients used by the appender, including just having a factory which points to an instance (e.g. `RaygunClientFactoryMethod.From(() => _preconfiguredInstance`).

This has been merged into release `4.2.0`.
